# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- counter
- recent_posts
- category
- tag
#- tagcloud
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
analytics: true
favicon: /favicon.png
twitter: pengisgood
google_plus: pengisgood
fb_admins:
fb_app_id:
